/**
 *
 * @author Jedaboy/Mateus Oliveira(Lawliet)/Guilherme Leme
 */
package views;

import controllers.GerenciadorDeFluxo;
import daoRepository.DaoFactory;
import daoRepository.UsuarioTCP;
import entities.MusicData;
import entities.Usuario;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class TelaDashBoard extends javax.swing.JFrame {

    boolean recomendacao = false;
    private Usuario usuario;
    private UsuarioTCP usuarioTCP;
    //secção de continuidade
    private MiniTela miniTela;
    private boolean playing = false;

    MusicData musicData;

    public void setDataAudio(MusicData musicData) {
        this.musicData = musicData;
    }

    public void setUsuAtual(Usuario usuario) {
        this.usuario = usuario;
    }

    public Usuario getUsuAtual() {
        return usuario;

    }

    public MiniTela getMiniTela() {
        return miniTela;

    }

    public void setMiniTela(MiniTela miniTela, boolean playing) {
        this.miniTela = miniTela;
        this.playing = playing;

    }

    /**
     * Creates new form TelaDashBoard
     */
    public TelaDashBoard(Usuario usuario, UsuarioTCP usuarioTCP) {
        //TALVEZ SEJA NECESSARIO PARA PASSAR A CONEXÃO PARA OUTRAS CLASSES
        if (usuario == null) {
            System.out.println("Usuario Null");
        }

        if (usuarioTCP == null) {
            System.out.println("Conexão Null DASHBOARD");
        }

        this.usuarioTCP = usuarioTCP;
        this.usuario = usuario;
        initComponents();

        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                try {
                    System.out.println("Encerramento na classe T.D");

                    //passa o usuario a ser encerrado
                    usuarioTCP.encerraSessao(usuario);
                } catch (IOException ex) {
                    Logger.getLogger(TelaDashBoard.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(TelaDashBoard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        avaliarLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        recomendacoesLabel = new javax.swing.JLabel();
        generoFavLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/logo_redondo.png")).getImage());
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        jLabel7.setText("Avaliar músicas");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 361, -1, 30));

        jLabel6.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        jLabel6.setText("Quero recomendações");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 533, 220, 30));

        jLabel5.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        jLabel5.setText("Meus Gêneros Preferidos");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 260, 30));

        avaliarLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_3.png"))); // NOI18N
        avaliarLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        avaliarLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                avaliarLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                avaliarLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                avaliarLabelMouseExited(evt);
            }
        });
        jPanel1.add(avaliarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 330, 430, 90));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("← ");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        recomendacoesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_3.png"))); // NOI18N
        recomendacoesLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recomendacoesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recomendacoesLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recomendacoesLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recomendacoesLabelMouseExited(evt);
            }
        });
        jPanel1.add(recomendacoesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 500, 430, 90));

        generoFavLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_3.png"))); // NOI18N
        generoFavLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generoFavLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generoFavLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                generoFavLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                generoFavLabelMouseExited(evt);
            }
        });
        jPanel1.add(generoFavLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 160, 430, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/a.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 690));
        jLabel1.getAccessibleContext().setAccessibleDescription("\"/images/a.png\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void generoFavLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generoFavLabelMouseClicked
        GerenciadorDeFluxo chamaMain = new GerenciadorDeFluxo();
        //informa qual tela deve ser exibida em seguida, neste caso a tela dashboard
        chamaMain.setContFlux(3);
        //passa o id do usuario Atual para a classe gerenciador de fluxo
        chamaMain.setUsuAtual(usuario);
        chamaMain.setUsuTCPAtual(usuarioTCP);

        //chama a clase fluxo principal que chamara a classe gerenciador de tela para exibir a tela desejada
        chamaMain.fluxoPrincipal();
        // fecha a janela atual
        if (miniTela != null) {
            miniTela.dispose();
            musicData.clipStop();
        }
        dispose();
    }//GEN-LAST:event_generoFavLabelMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        try {
            // seta de retorno esta invisivel por estar por debaixo do jPanel, esta no canto esquerdo superior
            GerenciadorDeFluxo chamaMain = new GerenciadorDeFluxo();
            chamaMain.setContFlux(0);
            chamaMain.fluxoPrincipal();
            if (miniTela != null) {
                miniTela.dispose();
                musicData.clipStop();
            }
            dispose();
            
        } catch (Exception ex) {
            Logger.getLogger(TelaDashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setForeground(Color.MAGENTA);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setForeground(Color.gray);
    }//GEN-LAST:event_jLabel4MouseExited

    private void avaliarLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avaliarLabelMouseClicked

        try {
            GerenciadorDeFluxo chamaMain = new GerenciadorDeFluxo(musicData);
            //informa qual tela deve ser exibida em seguida, neste caso a tela dashboard
            chamaMain.setContFlux(4);
            //passa o id do usuario Atual para a classe gerenciador de fluxo
            chamaMain.setUsuAtual(usuario);

            chamaMain.setRecomendacao(recomendacao);
            //chama a clase fluxo principal que chamara a classe gerenciador de tela para exibir a tela desejada
            chamaMain.fluxoPrincipal();
            // fecha a janela atual

            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(TelaDashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(TelaDashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TelaDashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(TelaDashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_avaliarLabelMouseClicked

    private void recomendacoesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recomendacoesLabelMouseClicked
        try {
            recomendacao = true;

            GerenciadorDeFluxo chamaMain = new GerenciadorDeFluxo(musicData);
            //informa qual tela deve ser exibida em seguida, neste caso a tela dashboard
            chamaMain.setContFlux(4);
            //passa o id do usuario Atual para a classe gerenciador de fluxo
            chamaMain.setUsuAtual(usuario);
            chamaMain.setMiniTela(miniTela, playing);
            chamaMain.setRecomendacao(recomendacao);

            //chama a clase fluxo principal que chamara a classe gerenciador de tela para exibir a tela desejada
            chamaMain.fluxoPrincipal();
            // fecha a janela atual
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(TelaDashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(TelaDashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TelaDashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(TelaDashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_recomendacoesLabelMouseClicked

    private void generoFavLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generoFavLabelMouseEntered
        generoFavLabel.setIcon(new ImageIcon(getClass().getResource("/images/pressbutton_3.png")));
    }//GEN-LAST:event_generoFavLabelMouseEntered

    private void generoFavLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generoFavLabelMouseExited
        generoFavLabel.setIcon(new ImageIcon(getClass().getResource("/images/button_3.png")));
    }//GEN-LAST:event_generoFavLabelMouseExited

    private void recomendacoesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recomendacoesLabelMouseEntered
        recomendacoesLabel.setIcon(new ImageIcon(getClass().getResource("/images/pressbutton_3.png")));
    }//GEN-LAST:event_recomendacoesLabelMouseEntered

    private void recomendacoesLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recomendacoesLabelMouseExited
        recomendacoesLabel.setIcon(new ImageIcon(getClass().getResource("/images/button_3.png")));
    }//GEN-LAST:event_recomendacoesLabelMouseExited

    private void avaliarLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avaliarLabelMouseEntered
        avaliarLabel.setIcon(new ImageIcon(getClass().getResource("/images/pressbutton_3.png")));
    }//GEN-LAST:event_avaliarLabelMouseEntered

    private void avaliarLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_avaliarLabelMouseExited
        avaliarLabel.setIcon(new ImageIcon(getClass().getResource("/images/button_3.png")));
    }//GEN-LAST:event_avaliarLabelMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avaliarLabel;
    private javax.swing.JLabel generoFavLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel recomendacoesLabel;
    // End of variables declaration//GEN-END:variables
}
